### ISSUE TITLE
Add support for cflinuxfs4 stack

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/r-buildpack-release#2]
Hi Buildpack Developers,

can you please add support for the cflinuxfs4 stack? We have already an experimental ops file for cf-deployment to enable the new stack:
https://github.com/cloudfoundry/cf-deployment/blob/main/operations/experimental/add-cflinuxfs4.yml

There is also a job in the cf-deployment release pipeline which runs CATs with cflinuxfs4:
https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-cats-cflinuxfs4

The current state of the cflinuxfs4 integration in cf-deployment is maintained in this issue:
https://github.com/cloudfoundry/cf-deployment/issues/989

Thanks and Best Regards,

  Jochen on behalf of the ARD WG.

**Comment by arjun024** [comment]
Tasks:
* [x] Build dependency & add to dependency/buildpack pipeline: [PR](https://github.com/cloudfoundry/buildpacks-ci/pull/218)
* [x] Get tests passing and release buildpack
* [x] Add cflinuxfs4 support to buildpack bosh releases

**Comment by arjun024** [comment]
https://github.com/cloudfoundry/r-buildpack-release/releases/tag/1.2.0
https://github.com/cloudfoundry/r-buildpack/releases/tag/v1.2.0

**Comment by jochenehret** [comment]
Integration into cf-deployment: https://github.com/cloudfoundry/cf-deployment/pull/1045
